/*
 * StudentZK crypto C-ABI header.
 *
 * Generated by hand to mirror crypto-core/src/ffi.rs. Hand-written rather than
 * cbindgen-generated because the surface is six functions / two structs /
 * five status codes and cbindgen would add a build-time dependency for no real
 * gain. If lib.rs/ffi.rs symbols change, mirror the change here.
 *
 * Memory model:
 *   - All ByteBuf outputs are heap-allocated by the library; the caller MUST
 *     call studentzkp_buf_free exactly once on each successful out-buffer.
 *   - All ByteSlice inputs are caller-owned; the library never frees them.
 *   - All functions return STUDENTZKP_OK (0) on success. On non-zero, call
 *     studentzkp_last_error to retrieve a UTF-8 error message (per-thread).
 *
 * Threading:
 *   - All entry points are thread-safe and may be called concurrently.
 *   - The last-error string is thread-local.
 */

#ifndef STUDENTZKP_CRYPTO_H
#define STUDENTZKP_CRYPTO_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Status codes — kept stable; consumers hard-code these. */
#define STUDENTZKP_OK                 0
#define STUDENTZKP_ERR_NULL_POINTER   1
#define STUDENTZKP_ERR_INVALID_INPUT  2
#define STUDENTZKP_ERR_CRYPTO         3
#define STUDENTZKP_ERR_INTERNAL       4

/* Library-owned heap buffer. Free with studentzkp_buf_free. */
typedef struct {
    uint8_t *ptr;
    size_t   len;
    size_t   cap;
} StudentZkpByteBuf;

/* Caller-owned read-only byte view. Pointer must outlive the call. */
typedef struct {
    const uint8_t *ptr;
    size_t         len;
} StudentZkpByteSlice;

/*
 * Generates a fresh BBS+ keypair on BLS12-381.
 * out_public_key, out_secret_key: ark-serialize compressed bytes.
 */
int32_t studentzkp_bbs_keygen(
    StudentZkpByteBuf *out_public_key,
    StudentZkpByteBuf *out_secret_key);

/*
 * Signs a sequence of attribute messages with a BBS+ secret key.
 * messages: pointer to messages_count ByteSlice entries (each one attribute).
 */
int32_t studentzkp_bbs_sign(
    const StudentZkpByteSlice *messages,
    size_t                     messages_count,
    StudentZkpByteSlice        secret_key,
    StudentZkpByteBuf         *out_signature);

/*
 * Derives a selective-disclosure proof from an existing BBS+ signature.
 * disclosed_indices: indices into messages[] to reveal in plaintext.
 */
int32_t studentzkp_bbs_derive_proof(
    StudentZkpByteSlice        signature,
    const StudentZkpByteSlice *messages,
    size_t                     messages_count,
    const size_t              *disclosed_indices,
    size_t                     disclosed_count,
    StudentZkpByteSlice        nonce,
    StudentZkpByteBuf         *out_proof);

/*
 * Verifies a BBS+ selective-disclosure proof.
 * out_valid: set to 1 if the proof verifies, 0 otherwise (only on STUDENTZKP_OK).
 */
int32_t studentzkp_bbs_verify_proof(
    StudentZkpByteSlice        proof,
    StudentZkpByteSlice        public_key,
    const size_t              *disclosed_indices,
    size_t                     disclosed_count,
    const StudentZkpByteSlice *disclosed_messages,
    size_t                     disclosed_messages_count,
    size_t                     total_message_count,
    StudentZkpByteSlice        nonce,
    uint8_t                   *out_valid);

/* Frees a library-allocated ByteBuf. NULL and double-free are safe no-ops. */
void studentzkp_buf_free(StudentZkpByteBuf *buf);

/*
 * Copies the current thread's last error (if any) into out_err.
 * out_err.len == 0 means no error is stored.
 * Returns STUDENTZKP_ERR_NULL_POINTER if out_err is NULL.
 */
int32_t studentzkp_last_error(StudentZkpByteBuf *out_err);

#ifdef __cplusplus
}
#endif

#endif /* STUDENTZKP_CRYPTO_H */
